#手提本地库
server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /demo

spring:
  profiles:
    active: MIlaptop
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false
    username: root
    password: 123456
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
      driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

    #指定资源文件夹路径
  thymeleaf:
      prefix: classpath:/view/
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
       hibernate:
         dialect : org.hibernate.dialect.MySQL5Dialect