CREATE TABLE `job_seeker` (
  `id` INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR ( 255 ) DEFAULT NULL COMMENT '中文名',
  `english_name` VARCHAR ( 255 ) DEFAULT NULL COMMENT '英文名',
  `sex` INT ( 1 ) DEFAULT NULL COMMENT '性别：1为男，0为女',
  `hometown` VARCHAR ( 255 ) DEFAULT NULL COMMENT '籍贯',
  `shool` VARCHAR ( 255 ) DEFAULT NULL COMMENT '学校',
  `major` VARCHAR ( 255 ) DEFAULT NULL COMMENT '专业',
  `educational_background` VARCHAR ( 255 ) DEFAULT NULL COMMENT '学历',
  `qq_num` INT ( 11 ) DEFAULT NULL COMMENT 'QQ号码',
  `tel_num` INT ( 11 ) DEFAULT NULL COMMENT '电话',\
  `birthday` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '出生日期',
  PRIMARY KEY ( `id` )
) ENGINE = INNODB AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8;